name: workflow1
# trigger
on:
  push:
    branches: ["main"]
env:
  TEXT: "Gabriel Gonzalez"
# pipeline
jobs:
  print: # job name
# ejecuta el pipeline en una VM Ubuntu
    runs-on: ubuntu-latest
# Ejecutar un print a consola
    steps:
      - name: print-to-screen
        run: echo "Mi Primer Workflow ${{ env.TEXT }}!"